/var/spool/slurmd/job88770/slurm_script: line 14: /home/ext-6401/anaconda3/bin/conda: No such file or directory
/var/spool/slurmd/job88770/slurm_script: line 15: /home/ext-6401/anaconda3/bin/conda: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 157, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ssd/ext-6401/PSCC-IPParis-Challenge/src/predict.py", line 64
    print(inputs.shape)
TabError: inconsistent use of tabs and spaces in indentation
